// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX3-eObInaDftbESeweS7pmKU9V4Y4AEI',
    appId: '1:267631338764:web:a47cb88ba225d3d6081529',
    messagingSenderId: '267631338764',
    projectId: 'flutter-fe_flutter',
    authDomain: 'flutter-fe_flutter.firebaseapp.com',
    storageBucket: 'flutter-fe_flutter.firebasestorage.app',
    measurementId: 'G-NX7CV0GD77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA4KqPu7IfdLjLR8X5QPATvB3kB6ykC28',
    appId: '1:267631338764:android:edecdfbf8bd10b9c081529',
    messagingSenderId: '267631338764',
    projectId: 'flutter-fe_flutter',
    storageBucket: 'flutter-fe_flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAes9MbZ0LVEnpLZNSw6q2rbTBNbA02d20',
    appId: '1:267631338764:ios:58f8f0acf7bb5722081529',
    messagingSenderId: '267631338764',
    projectId: 'flutter-fe_flutter',
    storageBucket: 'flutter-fe_flutter.firebasestorage.app',
    iosBundleId: 'com.example.feFlutter',
  );
}
