global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mediscan-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']  # For Docker on Mac/Windows
        # Use 'localhost:8000' if running Prometheus directly on host
        # or use the service name if using Docker Compose

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
