apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: ceb75a44-8902-415c-8ccb-e25c76c63f15

providers:
  - name: "ChestScan Dashboards"
    orgId: 1
    folder: ""
    folderUid: ""
    type: file
    disableDeletion: false
    editable: true
    updateIntervalSeconds: 10
    allowUiUpdates: true
    options:
      path: /etc/grafana/provisioning/dashboards
      foldersFromFilesStructure: true
