apiVersion: 1

providers:
  - name: "MediScan Dashboards"
    orgId: 1
    folder: ""
    folderUid: ""
    type: file
    disableDeletion: false
    editable: true
    updateIntervalSeconds: 10
    allowUiUpdates: true
    options:
      path: /etc/grafana/provisioning/dashboards
      foldersFromFilesStructure: true
