{
 "title": "Chest X-ray API Monitoring",
 "tags": [
  "fastapi",
  "chestscan"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests Completed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_request_count_total{job=\"fastapi-yolo\"})"
    }
   ]
  },
  {
   "title": "Failed Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "rate(app_failed_requests_total[1m])",
     "legendFormat": "{{endpoint}} ({{exception}})"
    }
   ]
  },
  {
   "title": "Average Response Time (5m)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(app_request_latency_seconds_sum[5m]) / rate(app_request_latency_seconds_count[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Average Request Latency (5m)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(app_request_latency_seconds_sum[1m]) / rate(app_request_latency_seconds_count[1m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Request Rate by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(app_request_count_total[1m])",
     "legendFormat": "{{endpoint}} ({{method}})"
    }
   ]
  },
  {
   "title": "Sum of Request",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"fastapi-yolo\"}"
    }
   ]
  },
  {
   "title": "Average Response Time (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(app_request_latency_seconds_sum[5m]) / rate(app_request_latency_seconds_count[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Request Rate by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_request_count_total[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}