name: Flutter Web Build and Deploy to Vercel

on:
  push:
    branches:
      - master
      - ci-cd-integration
      - fe_flutter
  pull_request:
    branches:
      - master
      - ci-cd-integration

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: fe_flutter

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.29.0"

    - name: Install dependencies
      run: |
        flutter pub get

    - name: Build Flutter web app
      run: |
        flutter build web --release
      env:
        FLUTTER_VERSION: "3.29.0"

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: flutter-web-build
        path: fe_flutter/build/web

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: flutter-web-build
        path: web-build

    - name: Install Vercel CLI
      run: |
        npm install -g vercel

    - name: Pull Vercel Project
      run: |
        vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

    - name: Deploy to Vercel
      run: |
        vercel build --cwd web-build --prod --token=${{ secrets.VERCEL_TOKEN }}
        vercel deploy --cwd web-build --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      
    - name: Clean up
      run: |
        rm -rf web-build/.vercel
